{% set name = "alibabacloud-tea-openapi" %}
{% set version = "0.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/alibabacloud_tea_openapi-{{ version }}.tar.gz
  sha256: 99796fa807433ee31e4e06239901d5dbc9cd22884f50f9bbb09b1dae9dbbb723

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - alibabacloud-tea-util >=0.3.11,<1.0.0
    - alibabacloud-credentials >=0.3.1,<1.0.0
    - alibabacloud-openapi-util >=0.2.1,<1.0.0
    - alibabacloud-gateway-spi >=0.0.1,<1.0.0
    - alibabacloud-tea-xml >=0.0.2,<1.0.0

test:
  imports:
    - alibabacloud_tea_openapi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aliyun/darabonba-openapi
  summary: Alibaba Cloud openapi SDK Library for Python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
