{% set name = "alibabacloud-tea-openapi" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/alibabacloud_tea_openapi-{{ version }}.tar.gz
  sha256: 2384b090870fdb089c3c40f3fb8cf0145b8c7d6c14abbac521f86a01abb5edaf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - alibabacloud-tea-util >=0.3.13,<1.0.0
    - alibabacloud-credentials >=1.0.2,<2.0.0
    - alibabacloud-openapi-util >=0.2.2,<1.0.0
    - alibabacloud-gateway-spi >=0.0.2,<1.0.0
    - alibabacloud-tea-xml >=0.0.2,<1.0.0
    - cryptography >=3.0.0,<45.0.0
    - darabonba-core >=1.0.3,<2.0.0

test:
  imports:
    - alibabacloud_tea_openapi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aliyun/darabonba-openapi
  summary: Alibaba Cloud openapi SDK Library for Python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
