{% set name = "alibabacloud-tea-openapi" %}
{% set version = "0.3.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/alibabacloud_tea_openapi-{{ version }}.tar.gz
  sha256: 6bffed8278597592e67860156f424bde4173a6599d7b6039fb640a3612bae292

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - alibabacloud-tea-util >=0.3.13,<1.0.0
    - alibabacloud-credentials >=1.0.2,<2.0.0
    - alibabacloud-openapi-util >=0.2.2,<1.0.0
    - alibabacloud-gateway-spi >=0.0.2,<1.0.0
    - alibabacloud-tea-xml >=0.0.2,<1.0.0

test:
  imports:
    - alibabacloud_tea_openapi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aliyun/darabonba-openapi
  summary: Alibaba Cloud openapi SDK Library for Python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
